"use client";
import { Toaster } from "sonner";
import ReduxProvider from "./common/Provider";
import Navbar from "./components/Navbar";
import "./globals.css";

// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <Navbar />
          {children}
        </ReduxProvider>
        <Toaster
          toastOptions={{
            style: {
              background: "#65c28c",
              color: "white",
            },
            className: "class",
          }}
        />
      </body>
    </html>
  );
}
